# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Actions on PR

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Load gradle cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew     
      - name: Build with Gradle
        run: ./gradlew clean build
  mutation_test:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Set up JDK 11
          uses: actions/setup-java@v2
          with:
            java-version: '11'
            distribution: 'adopt'
        - name: Grant execute permission for gradlew
          run: chmod +x gradlew

        - name: Build with Gradle
          run: ./gradlew clean assemble

        - name: Execute PITest
          run: |
            MUTATION_TEST=$(./gradlew pitest)     
            SUMMARY=${MUTATION_TEST##*=}
            echo 'summary_mutation<<EOF' >> $GITHUB_ENV      
            echo ${SUMMARY%%B*} | sed 's/>> /\n/g' >> $GITHUB_ENV
            echo 'EOF' >> $GITHUB_ENV
          id: mutation-test-execution
          shell: bash

        - name: Upload report
          uses: actions/upload-artifact@v2
          with:
            name: reports-artifact
            path: build/reports/pitest
            retention-days: 1

        - name: Comment
          uses: mshick/add-pr-comment@v1
          with:
            message: |
              ${{ env.summary_mutation }}
              
              *Check artifacts for the complete report*
            repo-token: ${{ secrets.GITHUB_TOKEN }}
            repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
            allow-repeats: true # This is the default
