# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Actions on PR

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew     
      - name: Execute PITest
        run: |
          MUTATION_TEST=$(./gradlew pitest)          
          echo "action_test=$MUTATION_TEST" >> $GITHUB_ENV
          echo "::set-output SUMMARY=${MUTATION_TEST#*=}"
        id: mutation-test-execution
        shell: bash
      - name: Test
        run: echo "${{ env.action_test }}"
      - name: Comment
        uses: mshick/add-pr-comment@v1
        with:
          message: ${{ steps.mutation-test-execution.outputs.SUMMARY }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
          allow-repeats: true # This is the default
